version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: nestjs_app
    env_file:
    - .env
    ports:
      - "7000:7000"
    depends_on:
      - db
    command: >
      
          sh -c "sleep 10 && npm run migration:run && npm run start:dev"

volumes:
  postgres_data:
